### PR TITLE
pkg/openshift: poll for additional things

### PR DESCRIPTION
**Pull request by jbpratt**
- pkg/clients/openshift/healthcheck: wait for job to exist
- pkg/clients/openshift/healthcheck: wrap errors
- pkg/openshift/rosa: poll until nightly version is found

### CODE REVIEW

**Comment by jbpratt** [comment]
/cc @ryankwilliams 

my only hold up with `692f5ee69bab8917248931b21328b1e905d99a9c` is whether we should poll for more than nightly builds but what if someone supplies a bad/incorrect version that will never exist?

**Comment by ryankwilliams** [comment]
> /cc @ryankwilliams
> 
> my only hold up with [692f5ee](https://github.com/openshift/osde2e-common/commit/692f5ee69bab8917248931b21328b1e905d99a9c) is whether we should poll for more than nightly builds but what if someone supplies a bad/incorrect version that will never exist?

@jbpratt As of now, I feel it would be okay to just currently only poll if the channel group is `nightly`. We can just take an assumption when its not `nightly` channel group, to assume the version is available. Also when `rosa create cluster` is invoked, it would fail there as well saying `version X is invalid/not available`.

Regarding the incorrect/invalid version (e.g. lets say for nightly channel group), do we want to check the format of the version to ensure it matches what rosa is looking for `4.13.0-0.nightly-2023-07-26-101700`?

**Comment by jbpratt** [comment]
/unhold

@ryankwilliams ready to go

**Comment by jbpratt** [comment]
constraint stuff:

```go
    versions, err := rosap.Versions(ctx, "stable", false, ">=4.12 < 4.13")
    if err != nil {
        panic(err)
    }

    for _, version := range versions {
        fmt.Println(version.RawID)
    }
...
```

```
I0728 03:42:00.458706  441662 rosa.go:220] "ROSA version" version="1.2.24"
I0728 03:42:00.980910  441662 versions.go:54] "Getting rosa versions" channel_group="stable" hosted_cp=false ocm_environment=https://api.stage.openshift.com
I0728 03:42:00.980932  441662 rosa.go:55] "Command" rosa_command="rosa list versions --channel-group stable --output json"
I0728 03:42:01.319546  441662 versions.go:79] "ROSA versions retrieved!" channel_group="stable" hosted_cp=false ocm_environment=https://api.stage.openshift.com
4.12.25
4.12.24
4.12.23
4.12.22
4.12.21
4.12.20
4.12.19
4.12.18
4.12.17
4.12.16
4.12.15
4.12.14
4.12.13
4.12.12
```

**Review by ryankwilliams — APPROVED** [review]

**Pull request merged**
